// frontend/src/components/leads/LeadTable.vue
<template>
  <!-- Loading state -->
  <div v-if="loading" class="space-y-2 p-4">
    <div v-for="i in 8" :key="i" class="h-10 w-full rounded-lg bg-muted animate-pulse" />
  </div>

  <!-- Empty state -->
  <div v-else-if="leads.length === 0" class="flex flex-col items-center justify-center py-16 text-center">
    <div class="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center mb-4">
      <Eye class="w-7 h-7 text-muted-foreground" />
    </div>
    <p class="text-sm font-medium text-foreground mb-1">Aucun lead trouvé</p>
    <p class="text-xs text-muted-foreground">Ajustez vos filtres ou ajoutez un nouveau lead</p>
  </div>

  <!-- Table -->
  <div v-else class="overflow-x-auto">
    <table class="w-full text-sm">
      <thead>
        <tr class="border-b border-border">
          <SortableHead field="nom"            label="Entreprise"  :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <SortableHead field="segment"        label="Segment"     :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <th class="text-[11px] font-medium text-muted-foreground px-4 py-3 text-left whitespace-nowrap">Secteur</th>
          <SortableHead field="ville"          label="Ville"       :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <th class="text-[11px] font-medium text-muted-foreground px-4 py-3 text-left whitespace-nowrap">SIREN</th>
          <SortableHead field="ca"             label="CA"          :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <SortableHead field="nbLocaux"       label="Locaux"      :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <SortableHead field="score"          label="Score"       :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <SortableHead field="completude"     label="Complétude"  :sort-field="sortField" :sort-dir="sortDir" @sort="emit('sort', $event)" />
          <th class="text-[11px] font-medium text-muted-foreground px-4 py-3 text-left whitespace-nowrap">Statut</th>
          <th class="text-[11px] font-medium text-muted-foreground px-4 py-3 text-right whitespace-nowrap">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="lead in leads"
          :key="lead.id"
          class="border-b border-border last:border-0 cursor-pointer hover:bg-muted/40 transition-colors group"
          @click="emit('preview', lead)"
        >
          <!-- Entreprise -->
          <td class="px-4 py-3 max-w-[180px]">
            <div class="flex flex-col">
              <span class="font-medium text-sm text-foreground truncate">{{ lead.nom }}</span>
              <span v-if="lead.hasBoamp" class="mt-0.5">
                <span class="text-[10px] font-semibold px-1.5 py-0.5 rounded-sm bg-blue-50 text-tacir-blue border border-blue-200">BOAMP</span>
              </span>
            </div>
          </td>
          <!-- Segment -->
          <td class="px-4 py-3">
            <SegmentBadge :segment="lead.segment" />
          </td>
          <!-- Secteur -->
          <td class="px-4 py-3 text-xs text-muted-foreground max-w-[140px] truncate">
            {{ lead.secteurActivite }}
          </td>
          <!-- Ville -->
          <td class="px-4 py-3 text-xs">{{ lead.ville }}</td>
          <!-- SIREN -->
          <td class="px-4 py-3 text-xs font-mono text-muted-foreground">{{ lead.siren }}</td>
          <!-- CA -->
          <td class="px-4 py-3 text-xs font-medium">{{ lead.caFormatted }}</td>
          <!-- Locaux -->
          <td class="px-4 py-3 text-xs">{{ lead.nbLocaux ?? '—' }}</td>
          <!-- Score -->
          <td class="px-4 py-3">
            <ScoreRing :score="lead.score" />
          </td>
          <!-- Complétude -->
          <td class="px-4 py-3">
            <CompletionBar :value="lead.completude" />
          </td>
          <!-- Statut -->
          <td class="px-4 py-3">
            <StatusBadge :status="lead.status" />
          </td>
          <!-- Actions -->
          <td class="px-4 py-3 text-right">
            <div class="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
              <button
                class="h-7 w-7 flex items-center justify-center rounded hover:bg-muted"
                @click.stop="emit('navigate', lead)"
                title="Voir la fiche"
              >
                <Eye class="w-3.5 h-3.5" />
              </button>
              <button
                class="h-7 w-7 flex items-center justify-center rounded hover:bg-muted"
                @click.stop="emit('edit', lead)"
                title="Modifier"
              >
                <Pencil class="w-3.5 h-3.5" />
              </button>
              <button
                class="h-7 w-7 flex items-center justify-center rounded hover:bg-destructive/10 hover:text-destructive"
                @click.stop="emit('delete', lead)"
                title="Supprimer"
              >
                <Trash2 class="w-3.5 h-3.5" />
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { Eye, Pencil, Trash2, ChevronDown, ChevronUp } from 'lucide-vue-next'
import SegmentBadge from './SegmentBadge.vue'
import StatusBadge  from './StatusBadge.vue'
import ScoreRing    from './ScoreRing.vue'
import CompletionBar from './CompletionBar.vue'
import SortableHead  from './SortableHead.vue'

const props = defineProps({
  leads:     { type: Array, required: true },
  sortField: { type: String, required: true },
  sortDir:   { type: String, required: true },
  loading:   { type: Boolean, default: false },
})

const emit = defineEmits(['sort', 'preview', 'edit', 'delete', 'navigate'])
</script>

// frontend/src/lovable_source/components/LeadTable.tsx
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { SegmentBadge, StatusBadge, BoampBadge, ScoreRing, CompletionBar } from "./LeadBadges";
import { ChevronDown, ChevronUp, Eye, Pencil, Trash2 } from "lucide-react";
import type { UILead } from "@/types/lead";
import type { SortField, SortDir } from "@/hooks/use-leads";
import { Skeleton } from "@/components/ui/skeleton";

interface Props {
  leads: UILead[];
  sortField: SortField;
  sortDir: SortDir;
  onSort: (field: SortField) => void;
  onPreview: (lead: UILead) => void;
  onEdit: (lead: UILead) => void;
  onDelete: (lead: UILead) => void;
  onNavigate: (lead: UILead) => void;
  loading?: boolean;
}

function SortIcon({ field, current, dir }: { field: SortField; current: SortField; dir: SortDir }) {
  if (field !== current) return <ChevronDown className="w-3 h-3 opacity-30" />;
  return dir === "asc" ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />;
}

function SortableHead({ field, label, current, dir, onSort }: {
  field: SortField; label: string; current: SortField; dir: SortDir; onSort: (f: SortField) => void;
}) {
  return (
    <TableHead
      className="cursor-pointer select-none hover:bg-muted/50 transition-colors text-[11px] font-medium whitespace-nowrap"
      onClick={() => onSort(field)}
    >
      <span className="flex items-center gap-1">
        {label}
        <SortIcon field={field} current={current} dir={dir} />
      </span>
    </TableHead>
  );
}

export function LeadTable({ leads, sortField, sortDir, onSort, onPreview, onEdit, onDelete, onNavigate, loading }: Props) {
  if (loading) {
    return (
      <div className="space-y-2 p-4">
        {Array.from({ length: 8 }).map((_, i) => (
          <Skeleton key={i} className="h-10 w-full rounded-lg" />
        ))}
      </div>
    );
  }

  if (leads.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center">
        <div className="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center mb-4">
          <Eye className="w-7 h-7 text-muted-foreground" />
        </div>
        <p className="text-sm font-medium text-foreground mb-1">Aucun lead trouvé</p>
        <p className="text-xs text-muted-foreground">Ajustez vos filtres ou ajoutez un nouveau lead</p>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <Table>
        <TableHeader>
          <TableRow className="hover:bg-transparent">
            <SortableHead field="nom" label="Entreprise" current={sortField} dir={sortDir} onSort={onSort} />
            <SortableHead field="segment" label="Segment" current={sortField} dir={sortDir} onSort={onSort} />
            <TableHead className="text-[11px] font-medium whitespace-nowrap">Secteur</TableHead>
            <SortableHead field="ville" label="Ville" current={sortField} dir={sortDir} onSort={onSort} />
            <TableHead className="text-[11px] font-medium whitespace-nowrap">SIREN</TableHead>
            <SortableHead field="ca" label="CA" current={sortField} dir={sortDir} onSort={onSort} />
            <SortableHead field="nbLocaux" label="Locaux" current={sortField} dir={sortDir} onSort={onSort} />
            <SortableHead field="score" label="Score" current={sortField} dir={sortDir} onSort={onSort} />
            <SortableHead field="completude" label="Complétude" current={sortField} dir={sortDir} onSort={onSort} />
            <TableHead className="text-[11px] font-medium whitespace-nowrap">Statut</TableHead>
            <TableHead className="text-[11px] font-medium whitespace-nowrap text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {leads.map((lead) => (
            <TableRow
              key={lead.id}
              className="cursor-pointer hover:bg-muted/40 transition-colors group"
              onClick={() => onPreview(lead)}
            >
              <TableCell className="font-medium text-sm max-w-[180px] truncate">
                <div>
                  <span className="text-foreground">{lead.nom}</span>
                  {lead.hasBoamp && <BoampBadge />}
                </div>
              </TableCell>
              <TableCell><SegmentBadge segment={lead.segment} /></TableCell>
              <TableCell className="text-xs text-muted-foreground max-w-[140px] truncate">{lead.secteurActivite}</TableCell>
              <TableCell className="text-xs">{lead.ville}</TableCell>
              <TableCell className="text-xs font-mono text-muted-foreground">{lead.siren}</TableCell>
              <TableCell className="text-xs font-medium">{lead.caFormatted}</TableCell>
              <TableCell className="text-xs">{lead.nbLocaux ?? "—"}</TableCell>
              <TableCell><ScoreRing score={lead.score} /></TableCell>
              <TableCell><CompletionBar value={lead.completude} /></TableCell>
              <TableCell><StatusBadge status={lead.status} /></TableCell>
              <TableCell className="text-right">
                <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Button
                    variant="ghost" size="icon" className="h-7 w-7"
                    onClick={(e) => { e.stopPropagation(); onNavigate(lead); }}
                  >
                    <Eye className="w-3.5 h-3.5" />
                  </Button>
                  <Button
                    variant="ghost" size="icon" className="h-7 w-7"
                    onClick={(e) => { e.stopPropagation(); onEdit(lead); }}
                  >
                    <Pencil className="w-3.5 h-3.5" />
                  </Button>
                  <Button
                    variant="ghost" size="icon" className="h-7 w-7 hover:bg-destructive/10 hover:text-destructive"
                    onClick={(e) => { e.stopPropagation(); onDelete(lead); }}
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
