// react_segmentation_folder/components/market/InsightsPanel.tsx
import { Card } from "@/components/ui/card";
import { Lightbulb, TrendingUp, Users, Target, Sparkles } from "lucide-react";
import type { LucideIcon } from "lucide-react";

interface Insight {
  icon: LucideIcon;
  iconColor: string;
  iconBg: string;
  title: string;
  text: string;
}

const INSIGHTS: Insight[] = [
  {
    icon: TrendingUp,
    iconColor: "text-tacir-blue",
    iconBg: "bg-tacir-blue/10",
    title: "Plus forte valeur moyenne",
    text: "Les grands groupes matures concentrent la plus forte valeur économique unitaire et justifient une approche enterprise dédiée.",
  },
  {
    icon: Target,
    iconColor: "text-tacir-lightblue",
    iconBg: "bg-tacir-lightblue/10",
    title: "Meilleur équilibre volume / valeur",
    text: "Les ETI établies diversifiées offrent le compromis optimal — volume significatif et valeur économique soutenue.",
  },
  {
    icon: Users,
    iconColor: "text-tacir-green",
    iconBg: "bg-tacir-green/10",
    title: "Approche self-serve",
    text: "Les petites structures jeunes sont mieux servies par une expérience self-serve scalable plutôt que par du sales direct.",
  },
  {
    icon: Sparkles,
    iconColor: "text-tacir-darkblue",
    iconBg: "bg-tacir-darkblue/10",
    title: "Niche à forte valeur",
    text: "Le segment commerce de gros est volumétriquement réduit mais sa valeur unitaire en fait une cible vente conseil rentable.",
  },
];

export function InsightsPanel() {
  return (
    <Card className="p-5 rounded-xl">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-tacir-yellow/10 flex items-center justify-center">
          <Lightbulb className="w-4 h-4 text-tacir-yellow" />
        </div>
        <div>
          <h3 className="font-semibold text-foreground text-sm">Insights clés</h3>
          <p className="text-xs text-muted-foreground">Recommandations exécutives</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {INSIGHTS.map((insight, i) => {
          const Icon = insight.icon;
          return (
            <div
              key={i}
              className="flex gap-3 p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors"
            >
              <div className={`w-8 h-8 rounded-lg ${insight.iconBg} flex items-center justify-center shrink-0`}>
                <Icon className={`w-4 h-4 ${insight.iconColor}`} />
              </div>
              <div className="min-w-0">
                <div className="text-xs font-semibold text-foreground mb-1">{insight.title}</div>
                <p className="text-xs text-muted-foreground leading-relaxed">{insight.text}</p>
              </div>
            </div>
          );
        })}
      </div>
    </Card>
  );
}

// frontend/src/components/market/InsightsPanel.vue
<template>
  <div class="bg-white border border-border rounded-xl p-5 shadow-sm">
    <h3 class="font-semibold text-tacir-darkblue text-sm mb-4">
      <Lightbulb class="inline w-4 h-4 mr-1 text-yellow-500" />
      Insights stratégiques
    </h3>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
      <div
        v-for="insight in insights"
        :key="insight.title"
        class="flex gap-3 p-3 rounded-lg border border-border bg-gray-50"
      >
        <component :is="insight.icon" class="w-4 h-4 shrink-0 mt-0.5" :class="insight.iconClass" />
        <div>
          <p class="text-xs font-semibold text-tacir-darkblue">{{ insight.title }}</p>
          <p class="text-xs text-tacir-darkgray mt-0.5 leading-relaxed">{{ insight.body }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { Lightbulb, TrendingUp, Target, Zap, AlertTriangle, Users } from "lucide-vue-next";

const insights = [
  {
    icon: TrendingUp, iconClass: "text-blue-500",
    title: "Grands groupes — levier principal",
    body:  "395 leads représentent ~37% du portefeuille avec un CA moyen de 2.9 Md€. Prioriser les RDV stratégiques et cycles longs.",
  },
  {
    icon: Target, iconClass: "text-cyan-500",
    title: "ETI établies — meilleur ROI volume/valeur",
    body:  "378 leads à 292 M€ CA moyen. Approche account-based et relationship selling pour maximiser le taux de conversion.",
  },
  {
    icon: Zap, iconClass: "text-green-500",
    title: "Petites structures — scalabilité self-serve",
    body:  "204 leads avec faible CA. Automatiser l'onboarding et proposer des offres freemium pour capturer ce volume efficacement.",
  },
  {
    icon: AlertTriangle, iconClass: "text-yellow-500",
    title: "PME énergie & retail — niche à fort potentiel",
    body:  "Seulement 46 leads mais CA moyen de 183 M€. Développer une offre sectorielle verticale dédiée énergie/retail.",
  },
  {
    icon: Users, iconClass: "text-purple-500",
    title: "ETI historiques — vente conseil premium",
    body:  "31 leads à 1.3 Md€ CA moyen. Profils anciens (59 ans) dans le commerce de gros — approche consultative longue durée.",
  },
  {
    icon: TrendingUp, iconClass: "text-tacir-blue",
    title: "Ile-de-France — concentration dominante",
    body:  "3 segments sur 5 ont l'Île-de-France comme région dominante. Renforcer la présence commerciale locale et les événements sectoriels parisiens.",
  },
];
</script>
