// react_segmentation_folder/components/market/SegmentRadarChart.tsx
import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Radar,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  ResponsiveContainer,
  Legend,
  Tooltip,
} from "recharts";
import type { MarketSegment } from "@/lib/segments-data";

interface Props {
  segments: MarketSegment[];
}

const AXES = [
  "Taille entreprise",
  "Valeur économique",
  "Ancienneté",
  "Empreinte multi-sites",
  "Concentration géo.",
] as const;

// Normalize segment values to 0-100 for radar
function buildRadarData(selected: MarketSegment[]) {
  const maxEmp = Math.max(...selected.map((s) => s.avgEmployees), 1);
  const maxRev = Math.max(...selected.map((s) => s.avgRevenue), 1);
  const maxAge = Math.max(...selected.map((s) => s.avgAge), 1);
  const maxLoc = Math.max(...selected.map((s) => s.avgLocations), 1);

  return AXES.map((axis) => {
    const row: Record<string, string | number> = { axis };
    selected.forEach((s) => {
      let v = 0;
      switch (axis) {
        case "Taille entreprise":
          v = (s.avgEmployees / maxEmp) * 100;
          break;
        case "Valeur économique":
          v = (s.avgRevenue / maxRev) * 100;
          break;
        case "Ancienneté":
          v = (s.avgAge / maxAge) * 100;
          break;
        case "Empreinte multi-sites":
          v = (s.avgLocations / maxLoc) * 100;
          break;
        case "Concentration géo.":
          // Île-de-France dominance proxy
          v = s.dominantRegion === "Île-de-France" ? 90 : 50;
          break;
      }
      row[s.shortName] = Math.round(v);
    });
    return row;
  });
}

export function SegmentRadarChart({ segments }: Props) {
  const [selected, setSelected] = useState<string[]>(() =>
    segments.slice(0, 3).map((s) => s.id),
  );

  const toggle = (id: string) => {
    setSelected((prev) => {
      if (prev.includes(id)) return prev.filter((x) => x !== id);
      if (prev.length >= 3) return [...prev.slice(1), id];
      return [...prev, id];
    });
  };

  const activeSegments = segments.filter((s) => selected.includes(s.id));
  const data = buildRadarData(activeSegments);

  return (
    <Card className="p-5 rounded-xl">
      <div className="flex items-start justify-between mb-4 flex-wrap gap-3">
        <div>
          <h3 className="font-semibold text-foreground text-sm">Comparaison multidimensionnelle</h3>
          <p className="text-xs text-muted-foreground">Sélectionnez jusqu'à 3 segments</p>
        </div>
        <div className="flex flex-wrap gap-1.5">
          {segments.map((s) => {
            const active = selected.includes(s.id);
            return (
              <button
                key={s.id}
                onClick={() => toggle(s.id)}
                className={`text-[11px] px-2.5 py-1 rounded-full border transition-all ${
                  active
                    ? "border-transparent text-white shadow-sm"
                    : "bg-background text-muted-foreground border-border hover:border-muted-foreground/40"
                }`}
                style={active ? { backgroundColor: s.color } : undefined}
              >
                {s.shortName}
              </button>
            );
          })}
        </div>
      </div>

      <div className="h-80">
        <ResponsiveContainer width="100%" height="100%">
          <RadarChart data={data} outerRadius="75%">
            <PolarGrid stroke="hsl(var(--border))" />
            <PolarAngleAxis dataKey="axis" tick={{ fontSize: 11, fill: "hsl(var(--foreground))" }} />
            <PolarRadiusAxis tick={{ fontSize: 9 }} stroke="hsl(var(--muted-foreground))" angle={90} />
            <Tooltip contentStyle={{ borderRadius: 8, fontSize: 12, border: "1px solid hsl(var(--border))" }} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            {activeSegments.map((s) => (
              <Radar
                key={s.id}
                name={s.shortName}
                dataKey={s.shortName}
                stroke={s.color}
                fill={s.color}
                fillOpacity={0.2}
              />
            ))}
          </RadarChart>
        </ResponsiveContainer>
      </div>
    </Card>
  );
}

// frontend/src/components/market/SegmentRadarChart.vue
<template>
  <div class="bg-white border border-border rounded-xl p-5 shadow-sm">
    <div class="flex items-start justify-between mb-3 flex-wrap gap-3">
      <div>
        <h3 class="font-semibold text-tacir-darkblue text-sm">Comparaison multidimensionnelle</h3>
        <p class="text-xs text-tacir-darkgray">Sélectionnez jusqu'à 3 segments</p>
      </div>
      <div class="flex flex-wrap gap-1.5">
        <button
          v-for="s in segments"
          :key="s.cluster"
          @click="toggle(s.cluster)"
          class="text-[11px] px-2.5 py-1 rounded-full border transition-all"
          :style="selected.includes(s.cluster)
            ? { backgroundColor: s.color, color: '#fff', border: `1px solid ${s.color}` }
            : { backgroundColor: 'transparent', color: '#666', border: '1px solid #ddd' }"
        >
          {{ shortLabel(s) }}
        </button>
      </div>
    </div>
    <v-chart class="h-72" :option="radarOption" autoresize />
  </div>
</template>

<script setup>
import { ref, computed } from "vue";
import VChart from "vue-echarts";
import { use } from "echarts/core";
import { RadarChart } from "echarts/charts";
import { RadarComponent, TooltipComponent, LegendComponent } from "echarts/components";
import { CanvasRenderer } from "echarts/renderers";

use([RadarChart, RadarComponent, TooltipComponent, LegendComponent, CanvasRenderer]);

const props = defineProps({ segments: { type: Array, default: () => [] } });

const selected = ref(props.segments.slice(0, 3).map(s => s.cluster));

function toggle(c) {
  if (selected.value.includes(c)) { selected.value = selected.value.filter(x => x !== c); }
  else if (selected.value.length < 3) { selected.value = [...selected.value, c]; }
  else { selected.value = [...selected.value.slice(1), c]; }
}

function shortLabel(s) { return s.label.split(" ").slice(0, 2).join(" "); }

const activeSegs = computed(() => props.segments.filter(s => selected.value.includes(s.cluster)));

const radarOption = computed(() => {
  const segs = activeSegs.value;
  if (!segs.length) return {};

  const maxEmp = Math.max(...segs.map(s => s.employes_moyen), 1);
  const maxCA  = Math.max(...segs.map(s => s.ca_moyen || 0), 1);
  const maxAge = Math.max(...segs.map(s => s.age_moyen), 1);
  const maxLoc = Math.max(...segs.map(s => s.nb_locaux_moyen || 0), 1);

  return {
    tooltip: {},
    legend:  { bottom: 0, textStyle: { fontSize: 11 } },
    radar:   {
      indicator: [
        { name: "Taille", max: 100 }, { name: "Valeur CA", max: 100 },
        { name: "Ancienneté", max: 100 }, { name: "Multi-sites", max: 100 },
        { name: "Concentr. géo", max: 100 },
      ],
      radius: "65%",
    },
    series: [{
      type: "radar",
      data: segs.map(s => ({
        name: shortLabel(s),
        value: [
          Math.round((s.employes_moyen / maxEmp) * 100),
          Math.round(((s.ca_moyen || 0) / maxCA) * 100),
          Math.round((s.age_moyen / maxAge) * 100),
          Math.round(((s.nb_locaux_moyen || 0) / maxLoc) * 100),
          s.region_dominante === "Ile-de-France" ? 90 : 50,
        ],
        lineStyle: { color: s.color, width: 2 },
        areaStyle: { color: s.color, opacity: 0.12 },
        itemStyle: { color: s.color },
      })),
    }],
  };
});
</script>
