// frontend/src/components/market/LeadsExplorerTable.vue
<template>
  <div class="bg-white border border-border rounded-xl shadow-sm overflow-hidden">
    <!-- Toolbar -->
    <div class="flex items-center justify-between gap-3 px-5 py-4 border-b border-border flex-wrap">
      <div>
        <h3 class="font-semibold text-tacir-darkblue text-sm">Explorateur de leads clusterisés</h3>
        <p class="text-xs text-tacir-darkgray">{{ total }} résultats</p>
      </div>
      <div class="flex items-center gap-2 flex-wrap">
        <!-- Segment filter -->
        <select
          v-model="selectedSegment"
          class="text-xs border border-border rounded-lg px-2.5 py-1.5 bg-white text-tacir-darkblue focus:outline-none focus:ring-1 focus:ring-tacir-blue"
        >
          <option :value="null">Tous les segments</option>
          <option v-for="s in segmentOptions" :key="s.cluster" :value="s.cluster">{{ s.label }}</option>
        </select>
        <!-- Search -->
        <div class="relative">
          <Search class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-tacir-darkgray" />
          <input
            v-model="search"
            type="text"
            placeholder="Rechercher..."
            class="text-xs pl-8 pr-3 py-1.5 border border-border rounded-lg bg-white text-tacir-darkblue placeholder:text-tacir-darkgray focus:outline-none focus:ring-1 focus:ring-tacir-blue w-44"
          />
        </div>
      </div>
    </div>

    <!-- Table -->
    <div class="overflow-x-auto">
      <table class="w-full text-xs">
        <thead class="bg-gray-50 border-b border-border">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-tacir-darkgray uppercase tracking-wider">Entreprise</th>
            <th class="px-4 py-3 text-left font-semibold text-tacir-darkgray uppercase tracking-wider">Segment</th>
            <th class="px-4 py-3 text-left font-semibold text-tacir-darkgray uppercase tracking-wider hidden md:table-cell">Secteur</th>
            <th class="px-4 py-3 text-left font-semibold text-tacir-darkgray uppercase tracking-wider hidden lg:table-cell">Ville</th>
            <th class="px-4 py-3 text-right font-semibold text-tacir-darkgray uppercase tracking-wider">CA</th>
            <th class="px-4 py-3 text-left font-semibold text-tacir-darkgray uppercase tracking-wider hidden xl:table-cell">Région</th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="loading">
            <td colspan="6" class="px-4 py-8 text-center text-tacir-darkgray">Chargement…</td>
          </tr>
          <tr
            v-else
            v-for="lead in leads"
            :key="lead.siren"
            class="border-b border-border/50 hover:bg-gray-50 transition-colors"
          >
            <td class="px-4 py-3">
              <div class="font-medium text-tacir-darkblue truncate max-w-[180px]">{{ lead.nom_entreprise || "—" }}</div>
              <div class="text-tacir-darkgray font-mono">{{ lead.siren }}</div>
            </td>
            <td class="px-4 py-3">
              <span
                class="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-medium border"
                :style="segmentStyle(lead.cluster)"
              >
                {{ lead.cluster_label }}
              </span>
            </td>
            <td class="px-4 py-3 hidden md:table-cell text-tacir-darkgray truncate max-w-[140px]">{{ lead.secteur_activite || "—" }}</td>
            <td class="px-4 py-3 hidden lg:table-cell text-tacir-darkgray">{{ lead.ville || "—" }}</td>
            <td class="px-4 py-3 text-right font-medium text-tacir-darkblue">{{ formatRevenue(lead.chiffre_affaires) }}</td>
            <td class="px-4 py-3 hidden xl:table-cell text-tacir-darkgray">{{ lead.region || "—" }}</td>
          </tr>
          <tr v-if="!loading && !leads.length">
            <td colspan="6" class="px-4 py-8 text-center text-tacir-darkgray">Aucun résultat.</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div class="flex items-center justify-between px-5 py-3 border-t border-border">
      <span class="text-xs text-tacir-darkgray">Page {{ page + 1 }}</span>
      <div class="flex gap-2">
        <button
          @click="page--"
          :disabled="page === 0"
          class="text-xs px-3 py-1.5 border border-border rounded-lg disabled:opacity-40 hover:bg-gray-50 text-tacir-darkblue"
        >
          Précédent
        </button>
        <button
          @click="page++"
          :disabled="(page + 1) * limit >= total"
          class="text-xs px-3 py-1.5 border border-border rounded-lg disabled:opacity-40 hover:bg-gray-50 text-tacir-darkblue"
        >
          Suivant
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, onMounted } from "vue";
import { Search } from "lucide-vue-next";
import { getLeads, formatRevenue, SEGMENT_META } from "@/services/segmentation.js";

const props = defineProps({ segments: { type: Array, default: () => [] } });

const leads          = ref([]);
const total          = ref(0);
const loading        = ref(false);
const page           = ref(0);
const limit          = 20;
const selectedSegment = ref(null);
const search         = ref("");

const segmentOptions = props.segments;

function segmentStyle(cluster) {
  const meta = SEGMENT_META[cluster] || { color: "#888" };
  return { backgroundColor: meta.color + "18", color: meta.color, borderColor: meta.color + "33" };
}

async function fetchLeads() {
  loading.value = true;
  try {
    const params = { skip: page.value * limit, limit };
    if (selectedSegment.value !== null) params.segment = selectedSegment.value;
    if (search.value)                    params.search  = search.value;
    const res  = await getLeads(params);
    leads.value = res.data.leads || [];
    total.value = res.data.total || 0;
  } catch (e) {
    leads.value = [];
    total.value = 0;
  } finally {
    loading.value = false;
  }
}

watch([page, selectedSegment], fetchLeads);
watch(search, () => { page.value = 0; fetchLeads(); });
onMounted(fetchLeads);
</script>

// react_segmentation_folder/components/market/LeadsExplorerTable.tsx
import { useMemo, useState } from "react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EXPLORER_LEADS, SEGMENTS, formatRevenue } from "@/lib/segments-data";
import type { ExplorerLead, MarketSegment } from "@/lib/segments-data";

const ALL = "__all__";

export function LeadsExplorerTable() {
  const [search, setSearch] = useState("");
  const [segmentFilter, setSegmentFilter] = useState(ALL);
  const [regionFilter, setRegionFilter] = useState(ALL);
  const [sectorFilter, setSectorFilter] = useState(ALL);
  const [categoryFilter, setCategoryFilter] = useState(ALL);
  const [revenueFilter, setRevenueFilter] = useState(ALL);

  const segmentMap = useMemo(() => {
    const map = new Map<string, MarketSegment>();
    SEGMENTS.forEach((s) => map.set(s.id, s));
    return map;
  }, []);

  const regions = useMemo(() => Array.from(new Set(EXPLORER_LEADS.map((l) => l.region))).sort(), []);
  const sectors = useMemo(() => Array.from(new Set(EXPLORER_LEADS.map((l) => l.secteur))).sort(), []);
  const categories = useMemo(() => Array.from(new Set(EXPLORER_LEADS.map((l) => l.categorie))).sort(), []);

  const filtered = useMemo(() => {
    return EXPLORER_LEADS.filter((l) => {
      if (segmentFilter !== ALL && l.segmentId !== segmentFilter) return false;
      if (regionFilter !== ALL && l.region !== regionFilter) return false;
      if (sectorFilter !== ALL && l.secteur !== sectorFilter) return false;
      if (categoryFilter !== ALL && l.categorie !== categoryFilter) return false;
      if (revenueFilter !== ALL) {
        const ca = l.ca ?? 0;
        if (revenueFilter === "lt1m" && ca >= 1_000_000) return false;
        if (revenueFilter === "1m-100m" && (ca < 1_000_000 || ca >= 100_000_000)) return false;
        if (revenueFilter === "100m-1b" && (ca < 100_000_000 || ca >= 1_000_000_000)) return false;
        if (revenueFilter === "gt1b" && ca < 1_000_000_000) return false;
      }
      if (search) {
        const q = search.toLowerCase();
        if (
          !l.nom.toLowerCase().includes(q) &&
          !l.ville.toLowerCase().includes(q) &&
          !l.siren.includes(q) &&
          !l.secteur.toLowerCase().includes(q)
        )
          return false;
      }
      return true;
    });
  }, [search, segmentFilter, regionFilter, sectorFilter, categoryFilter, revenueFilter]);

  const activeFilters =
    (segmentFilter !== ALL ? 1 : 0) +
    (regionFilter !== ALL ? 1 : 0) +
    (sectorFilter !== ALL ? 1 : 0) +
    (categoryFilter !== ALL ? 1 : 0) +
    (revenueFilter !== ALL ? 1 : 0) +
    (search ? 1 : 0);

  const reset = () => {
    setSearch("");
    setSegmentFilter(ALL);
    setRegionFilter(ALL);
    setSectorFilter(ALL);
    setCategoryFilter(ALL);
    setRevenueFilter(ALL);
  };

  return (
    <Card className="p-5 rounded-xl">
      <div className="flex items-start justify-between mb-4 flex-wrap gap-3">
        <div>
          <h3 className="font-semibold text-foreground text-sm">Explorateur de leads</h3>
          <p className="text-xs text-muted-foreground">
            {filtered.length} lead{filtered.length > 1 ? "s" : ""} affiché{filtered.length > 1 ? "s" : ""}
          </p>
        </div>
        {activeFilters > 0 && (
          <Button variant="ghost" size="sm" onClick={reset} className="h-8 text-xs">
            <X className="w-3 h-3 mr-1" /> Réinitialiser ({activeFilters})
          </Button>
        )}
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-2 mb-4">
        <div className="relative col-span-2 lg:col-span-2">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
          <Input
            placeholder="Rechercher..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9 h-9 text-sm"
          />
        </div>
        <Select value={segmentFilter} onValueChange={setSegmentFilter}>
          <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Segment" /></SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Tous segments</SelectItem>
            {SEGMENTS.map((s) => (
              <SelectItem key={s.id} value={s.id}>{s.shortName}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={regionFilter} onValueChange={setRegionFilter}>
          <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Région" /></SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Toutes régions</SelectItem>
            {regions.map((r) => <SelectItem key={r} value={r}>{r}</SelectItem>)}
          </SelectContent>
        </Select>
        <Select value={sectorFilter} onValueChange={setSectorFilter}>
          <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Secteur" /></SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Tous secteurs</SelectItem>
            {sectors.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
          </SelectContent>
        </Select>
        <Select value={categoryFilter} onValueChange={setCategoryFilter}>
          <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Catégorie" /></SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Toutes catégories</SelectItem>
            {categories.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}
          </SelectContent>
        </Select>
        <Select value={revenueFilter} onValueChange={setRevenueFilter}>
          <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="CA" /></SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Tous CA</SelectItem>
            <SelectItem value="lt1m">{"< 1 M€"}</SelectItem>
            <SelectItem value="1m-100m">1 – 100 M€</SelectItem>
            <SelectItem value="100m-1b">100 M€ – 1 Md€</SelectItem>
            <SelectItem value="gt1b">{"> 1 Md€"}</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="border rounded-lg overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow className="hover:bg-transparent bg-muted/30">
              <TableHead className="text-[11px] font-semibold">Entreprise</TableHead>
              <TableHead className="text-[11px] font-semibold">Segment</TableHead>
              <TableHead className="text-[11px] font-semibold">Secteur</TableHead>
              <TableHead className="text-[11px] font-semibold">Ville</TableHead>
              <TableHead className="text-[11px] font-semibold">SIREN</TableHead>
              <TableHead className="text-[11px] font-semibold text-right">CA</TableHead>
              <TableHead className="text-[11px] font-semibold text-right">Âge</TableHead>
              <TableHead className="text-[11px] font-semibold">Région</TableHead>
              <TableHead className="text-[11px] font-semibold">Catégorie</TableHead>
              <TableHead className="text-[11px] font-semibold">Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.map((lead) => {
              const seg = segmentMap.get(lead.segmentId);
              return (
                <ExplorerRow key={lead.id} lead={lead} segment={seg} />
              );
            })}
            {filtered.length === 0 && (
              <TableRow>
                <TableCell colSpan={10} className="text-center text-sm text-muted-foreground py-12">
                  Aucun lead ne correspond aux filtres.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
    </Card>
  );
}

function ExplorerRow({ lead, segment }: { lead: ExplorerLead; segment?: MarketSegment }) {
  return (
    <TableRow className="hover:bg-muted/30">
      <TableCell className="text-xs font-medium max-w-[200px] truncate">{lead.nom}</TableCell>
      <TableCell>
        {segment && (
          <span
            className="text-[10px] font-semibold px-2 py-0.5 rounded-full inline-block"
            style={{ backgroundColor: `${segment.color}1A`, color: segment.color }}
          >
            {segment.shortName}
          </span>
        )}
      </TableCell>
      <TableCell className="text-xs text-muted-foreground max-w-[140px] truncate">{lead.secteur}</TableCell>
      <TableCell className="text-xs">{lead.ville}</TableCell>
      <TableCell className="text-xs font-mono text-muted-foreground">{lead.siren}</TableCell>
      <TableCell className="text-xs font-medium text-right">{formatRevenue(lead.ca)}</TableCell>
      <TableCell className="text-xs text-right">{lead.age} ans</TableCell>
      <TableCell className="text-xs">{lead.region}</TableCell>
      <TableCell className="text-xs text-muted-foreground max-w-[160px] truncate">{lead.categorie}</TableCell>
      <TableCell>
        <Badge variant="outline" className="text-[10px] font-medium">{lead.action}</Badge>
      </TableCell>
    </TableRow>
  );
}
