// frontend/src/pages/commercial/LeadDetailPage.vue
<template>
  <div>
    <div class="flex min-h-screen bg-tacir-lightgray/30">

    <!-- Sidebar -->
    <TheSidebar />

    <!-- Main content -->
    <div class="flex-1 flex flex-col min-w-0">

      <!-- Header -->
      <header class="h-14 sm:h-16 border-b border-border bg-white sticky top-0 z-40 px-3 sm:px-6 flex items-center justify-between shadow-sm">
        <div class="flex items-center gap-2 sm:gap-3 min-w-0">
          <button
            @click="router.push('/commercial/leads')"
            class="w-8 h-8 flex-shrink-0 flex items-center justify-center rounded-lg hover:bg-tacir-lightgray text-tacir-darkgray transition-colors"
          >
            <ArrowLeft class="h-4 w-4" />
          </button>
          <span class="text-xs sm:text-sm text-muted-foreground truncate hidden xs:block sm:block">Mes leads / Fiche entreprise</span>
        </div>
        <div class="flex items-center gap-1.5 sm:gap-2 flex-shrink-0">
          <button
            @click="editOpen = true"
            class="inline-flex items-center gap-1.5 h-8 px-2 sm:px-3 text-sm rounded-md border border-input hover:bg-accent transition-colors"
          >
            <Pencil class="w-3.5 h-3.5" />
            <span class="hidden sm:inline">Modifier</span>
          </button>
          <button
            class="inline-flex items-center gap-1.5 h-8 px-2 sm:px-3 text-sm rounded-md border border-input hover:bg-destructive/10 hover:text-destructive transition-colors"
          >
            <Trash2 class="w-3.5 h-3.5" />
            <span class="hidden sm:inline">Supprimer</span>
          </button>
        </div>
      </header>

      <!-- Loading / Lead not found -->
      <div v-if="!displayLead" class="flex-1 flex items-center justify-center">
        <div v-if="isLoading" class="text-center space-y-3 flex flex-col items-center">
          <Loader2 class="h-8 w-8 animate-spin text-tacir-blue" />
          <p class="text-sm font-medium text-muted-foreground">Chargement...</p>
        </div>
        <div v-else class="text-center space-y-3">
          <p class="text-lg font-medium text-foreground">Lead introuvable</p>
          <button
            @click="router.push('/commercial/leads')"
            class="inline-flex items-center gap-2 h-9 px-4 text-sm rounded-md border border-input hover:bg-accent transition-colors"
          >
            <ArrowLeft class="w-4 h-4" /> Retour à la liste
          </button>
        </div>
      </div>

      <!-- Lead detail -->
      <main v-else class="flex-1 p-6 md:p-8 overflow-y-auto">
        <div class="max-w-[1100px] mx-auto space-y-6">

          <!-- Hero card -->
          <div class="bg-white rounded-xl border border-border shadow-card p-4 sm:p-6">
            <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
              <div class="flex items-center gap-3 sm:gap-4">
                <div class="w-12 h-12 sm:w-14 sm:h-14 rounded-xl bg-blue-50 flex items-center justify-center text-tacir-blue font-semibold text-lg sm:text-xl flex-shrink-0">
                  {{ initials }}
                </div>
                <div class="min-w-0">
                  <h1 class="text-lg sm:text-xl font-semibold text-foreground truncate">{{ displayLead.nom }}</h1>
                  <p class="text-xs sm:text-sm text-muted-foreground mt-0.5">
                    SIREN {{ displayLead.siren }} · {{ displayLead.ville }}, {{ displayLead.pays }}
                  </p>
                  <div class="flex flex-wrap gap-1.5 mt-2">
                    <SegmentBadge :segment="displayLead.segment" />
                    <StatusBadge  :status="displayLead.status"  />
                    <span
                      v-if="displayLead.hasBoamp"
                      class="text-[10px] font-semibold px-2 py-0.5 rounded-sm bg-blue-50 text-tacir-blue border border-blue-200"
                    >
                      BOAMP
                    </span>
                  </div>
                </div>
              </div>
              <!-- Metric chips — wrap naturally on mobile -->
              <div class="flex items-center gap-2 sm:gap-4 flex-wrap">
                <div class="text-center p-2.5 sm:p-3 rounded-xl bg-muted/50 min-w-[64px] sm:min-w-[70px]">
                  <ScoreRing :score="displayLead.score" size="md" />
                  <p class="text-[10px] text-muted-foreground mt-1">Score</p>
                </div>
                <div class="text-center p-2.5 sm:p-3 rounded-xl bg-muted/50 min-w-[64px] sm:min-w-[70px]">
                  <p class="text-base sm:text-lg font-semibold text-foreground">{{ displayLead.probaConversion }}%</p>
                  <p class="text-[10px] text-muted-foreground">Proba.</p>
                </div>
                <div class="text-center p-2.5 sm:p-3 rounded-xl bg-muted/50 min-w-[64px] sm:min-w-[70px]">
                  <p class="text-base sm:text-lg font-semibold text-foreground">{{ displayLead.completude }}%</p>
                  <p class="text-[10px] text-muted-foreground">Complétude</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Two-column detail -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Identité -->
            <div class="bg-white rounded-xl border border-border shadow-card p-5">
              <div class="flex items-center gap-2 mb-4">
                <div class="w-7 h-7 rounded-lg bg-blue-50 flex items-center justify-center">
                  <FileText class="w-3.5 h-3.5 text-tacir-blue" />
                </div>
                <h2 class="text-sm font-semibold">Identité</h2>
              </div>
              <InfoRow label="SIREN"              :value="displayLead.siren" />
              <InfoRow label="SIRET"              :value="displayLead.siret" />
              <InfoRow label="Identifiant"        :value="displayLead.identifiant" />
              <InfoRow label="Taille"             :value="displayLead.tailleEntreprise" badge />
              <InfoRow label="Forme juridique"    :value="displayLead.formeJuridique" />
              <InfoRow label="Date de création"   :value="displayLead.dateCreationFormatted" />
              <InfoRow label="Secteur d'activité" :value="displayLead.secteurActivite" />
              <InfoRow label="Chiffre d'affaires" :value="displayLead.caFormatted" highlight />
              <InfoRow label="Nb locaux"          :value="displayLead.nbLocaux?.toString() ?? '—'" />
            </div>

            <!-- Adresse & Contact -->
            <div class="bg-white rounded-xl border border-border shadow-card p-5">
              <div class="flex items-center gap-2 mb-4">
                <div class="w-7 h-7 rounded-lg bg-emerald-50 flex items-center justify-center">
                  <MapPin class="w-3.5 h-3.5 text-emerald-600" />
                </div>
                <h2 class="text-sm font-semibold">Adresse & contact</h2>
              </div>
              <InfoRow label="Adresse"     value="Non renseigné" muted />
              <InfoRow label="Code postal" :value="displayLead.codePostal" />
              <InfoRow label="Ville"       :value="displayLead.ville" />
              <InfoRow label="Région"      value="Non renseigné" muted />
              <InfoRow label="Pays"        :value="displayLead.pays" />
              <InfoRow label="Email"       :value="displayLead.email" link />
              <InfoRow label="Téléphone"   :value="displayLead.telephone" link />
              <InfoRow label="Site web"    value="Non renseigné" muted />
            </div>
          </div>

          <!-- Dirigeants -->
          <div class="bg-white rounded-xl border border-border shadow-card p-5">
            <div class="flex items-center gap-2 mb-4">
              <div class="w-7 h-7 rounded-lg bg-purple-50 flex items-center justify-center">
                <Users class="w-3.5 h-3.5 text-purple-600" />
              </div>
              <h2 class="text-sm font-semibold">
                Dirigeants & contacts ({{ displayLead.nbDirigeants }})
              </h2>
            </div>
            <p v-if="displayLead.dirigeants.length === 0" class="text-sm text-muted-foreground italic">
              Aucun dirigeant renseigné
            </p>
            <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div
                v-for="(d, i) in displayLead.dirigeants"
                :key="d.id"
                class="flex items-start gap-3 p-3 rounded-xl bg-muted/40 hover:bg-muted/60 transition-colors"
              >
                <div
                  :class="['w-10 h-10 rounded-full flex items-center justify-center text-sm font-semibold flex-shrink-0', AVATAR_COLORS[i % AVATAR_COLORS.length]]"
                >
                  {{ d.initials }}
                </div>
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-medium text-foreground truncate">{{ d.fullName }}</p>
                  <p class="text-[11px] text-muted-foreground">{{ d.qualite }}</p>
                  <div class="flex items-center gap-3 mt-1.5 flex-wrap">
                    <span class="text-[11px] text-muted-foreground italic">Email non renseigné</span>
                    <span class="text-[11px] text-muted-foreground italic">Tél. non renseigné</span>
                  </div>
                </div>
                <div class="flex flex-col items-end gap-1 flex-shrink-0">
                  <div v-if="d.age" class="text-center">
                    <span class="text-base font-semibold text-foreground">{{ d.age }}</span>
                    <span class="text-[10px] text-muted-foreground block">ans</span>
                  </div>
                  <a
                    v-if="d.linkedinUrl"
                    :href="d.linkedinUrl"
                    target="_blank"
                    rel="noreferrer"
                    class="text-blue-600 hover:text-blue-800"
                  >
                    <Linkedin class="w-4 h-4" />
                  </a>
                </div>
              </div>
            </div>
            <!-- Contact completeness -->
            <div class="flex items-center gap-3 mt-4 pt-4 border-t border-border">
              <span class="text-[11px] text-muted-foreground">Complétude contacts</span>
              <div class="flex-1 h-1.5 rounded-full bg-muted overflow-hidden">
                <div
                  class="h-full rounded-full bg-emerald-500 transition-all"
                  :style="{ width: `${contactCompleteness}%` }"
                />
              </div>
              <span class="text-xs font-medium text-emerald-600">{{ contactCompleteness }}%</span>
            </div>
          </div>

          <!-- Indicateurs métier -->
          <div class="bg-white rounded-xl border border-border shadow-card p-5">
            <div class="flex items-center gap-2 mb-4">
              <div class="w-7 h-7 rounded-lg bg-amber-50 flex items-center justify-center">
                <BarChart3 class="w-3.5 h-3.5 text-amber-600" />
              </div>
              <h2 class="text-sm font-semibold">Indicateurs métier</h2>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
              <MetricCard :icon="Target"     label="Score"             :value="`${displayLead.score}/100`" />
              <MetricCard :icon="TrendingUp" label="Proba. conversion" :value="`${displayLead.probaConversion}%`" />
              <MetricCard :icon="Activity"   label="Complétude"        :value="`${displayLead.completude}%`" />
              <MetricCard :icon="Users"      label="Nb dirigeants"     :value="`${displayLead.nbDirigeants}`" />
              <MetricCard :icon="Linkedin"   label="LinkedIn"          :value="displayLead.hasLinkedinDirigeant ? 'Oui' : 'Non'" />
              <MetricCard :icon="Mail"       label="Email"             :value="displayLead.hasEmail ? 'Oui' : 'Non'" />
              <MetricCard :icon="Phone"      label="Téléphone"         :value="displayLead.hasTelephone ? 'Oui' : 'Non'" />
              <MetricCard :icon="Clock"      label="Fraîcheur"         :value="displayLead.dateScrapingFormatted" />
            </div>
          </div>

          <!-- Métadonnées -->
          <div class="bg-white rounded-xl border border-border shadow-card p-5">
            <div class="flex items-center gap-2 mb-4">
              <div class="w-7 h-7 rounded-lg bg-muted flex items-center justify-center">
                <Database class="w-3.5 h-3.5 text-muted-foreground" />
              </div>
              <h2 class="text-sm font-semibold text-muted-foreground">Métadonnées & source</h2>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-3 gap-x-6">
              <InfoRow label="Date création entreprise" :value="displayLead.dateCreationFormatted" />
              <InfoRow label="Dernière modif. site"     :value="displayLead.dateDerniereModifFormatted" />
              <InfoRow label="Date scraping"            :value="displayLead.dateScrapingFormatted" />
              <InfoRow label="Créé le"                  :value="displayLead.createdAt ? formatDateFR(displayLead.createdAt) : '—'" />
              <InfoRow label="Mis à jour le"            :value="displayLead.updatedAt ? formatDateFR(displayLead.updatedAt) : '—'" />
              <InfoRow label="Raw Lead ID"              :value="displayLead.rawLeadId ?? '—'" />
            </div>
            <div v-if="displayLead.sources" class="mt-3 pt-3 border-t border-border">
              <p class="text-[11px] text-muted-foreground mb-1">Sources</p>
              <p class="text-xs font-mono text-muted-foreground bg-muted/50 rounded-lg p-2 overflow-x-auto">
                {{ JSON.stringify(displayLead.sources, null, 0).slice(0, 200) }}…
              </p>
            </div>
          </div>

          <!-- Actions -->
          <div class="flex justify-end gap-3 pb-8">
            <button class="inline-flex items-center gap-2 h-9 px-4 text-sm rounded-md border border-input hover:bg-accent transition-colors">
              <RefreshCw class="w-3.5 h-3.5" /> Prospects similaires
            </button>
            <button class="inline-flex items-center gap-2 h-9 px-4 text-sm font-medium rounded-md bg-tacir-blue text-white hover:opacity-90 transition-opacity">
              <TrendingUp class="w-3.5 h-3.5" /> Analyser le potentiel
            </button>
          </div>

        </div>
      </main>
    </div>
  </div>

  <!-- Edit modal -->
  <LeadEditModal
    v-if="displayLead"
    :lead="editOpen ? displayLead : null"
    :open="editOpen"
    @close="editOpen = false"
    @save="handleSave"
  />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  ArrowLeft, Pencil, Trash2, MapPin, Phone, Mail, Linkedin,
  Users, FileText, BarChart3, Target, TrendingUp, Activity,
  Clock, Database, RefreshCw, Loader2,
} from 'lucide-vue-next'

import TheSidebar    from '@/components/AppSidebar.vue'
import SegmentBadge  from '@/components/leads/SegmentBadge.vue'
import StatusBadge   from '@/components/leads/StatusBadge.vue'
import ScoreRing     from '@/components/leads/ScoreRing.vue'
import InfoRow       from '@/components/leads/InfoRow.vue'
import MetricCard    from '@/components/leads/MetricCard.vue'
import LeadEditModal from '@/components/leads/LeadEditModal.vue'

import axios from 'axios'
import { adaptLead, formatDateFR } from '@/lib/leadAdapter'

const route  = useRoute()
const router = useRouter()

const leadFromApi = ref(null)
const isLoading = ref(true)

// Local overrides for optimistic edits
const localLead  = ref(null)
const displayLead = computed(() => localLead.value ?? leadFromApi.value)

const editOpen = ref(false)

async function fetchLeadDetails() {
  isLoading.value = true
  try {
    const baseUrl = import.meta.env.VITE_FASTAPI_URL || 'http://localhost:8001'
    const res = await axios.get(`${baseUrl}/entreprises/${route.params.id}`)
    leadFromApi.value = adaptLead(res.data, 0)
  } catch (err) {
    console.error('[LeadDetail] Fetch error:', err)
  } finally {
    isLoading.value = false
  }
}

import { onMounted } from 'vue'

onMounted(() => {
  fetchLeadDetails()
})

// ---- Computed ----
const initials = computed(() => {
  if (!displayLead.value) return ''
  return displayLead.value.nom
    .split(/\s+/)
    .slice(0, 2)
    .map((w) => w[0] ?? '')
    .join('')
    .toUpperCase()
})

const contactCompleteness = computed(() => {
  if (!displayLead.value || displayLead.value.nbDirigeants === 0) return 0
  const withLinkedin = displayLead.value.dirigeants.filter((d) => d.linkedinUrl).length
  return Math.round((withLinkedin / displayLead.value.nbDirigeants) * 100)
})

// ---- Constants ----
const AVATAR_COLORS = [
  'bg-purple-50 text-purple-700',
  'bg-emerald-50 text-emerald-700',
  'bg-orange-50 text-orange-700',
  'bg-blue-50 text-blue-700',
  'bg-rose-50 text-rose-700',
]

// ---- Handlers ----
function handleSave(id, updates) {
  localLead.value = { ...(displayLead.value ?? {}), ...updates }
  editOpen.value = false
}
</script>

<style scoped>
.shadow-card {
  box-shadow: 0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(48,62,140,0.06);
}
</style>

// frontend/src/lovable_source/pages/LeadDetailPage.tsx
import { useParams, useNavigate, Link } from "react-router-dom";
import { useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { SegmentBadge, StatusBadge, BoampBadge, ScoreRing, CompletionBar } from "@/components/leads/LeadBadges";
import { LeadEditModal } from "@/components/leads/LeadEditModal";
import {
  ArrowLeft, Building2, MapPin, Phone, Mail, Globe, Linkedin,
  Users, Calendar, FileText, BarChart3, Pencil, Trash2, RefreshCw,
  Target, TrendingUp, Activity, Clock, Database,
} from "lucide-react";
import type { UILead, UIDirigeant } from "@/types/lead";
import type { RawLeadResponse } from "@/types/lead";
import { adaptLeadResponse, formatDateFR } from "@/lib/lead-adapter";
import mockData from "@/data/mock-leads.json";
import { toast } from "sonner";

export default function LeadDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const allLeads = useMemo(() => adaptLeadResponse((mockData as RawLeadResponse).data), []);
  const lead = allLeads.find((l) => l.id === id);

  const [editOpen, setEditOpen] = useState(false);
  const [currentLead, setCurrentLead] = useState<UILead | null>(null);

  if (!lead) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <p className="text-lg font-medium text-foreground mb-2">Lead introuvable</p>
          <Link to="/leads"><Button variant="outline" className="gap-2"><ArrowLeft className="w-4 h-4" />Retour</Button></Link>
        </div>
      </div>
    );
  }

  const displayLead = currentLead ?? lead;
  const initials = displayLead.nom.split(/\s+/).slice(0, 2).map((w) => w[0]).join("").toUpperCase();

  // Avatar colors
  const AVATAR_COLORS = [
    "bg-purple-50 text-purple-700",
    "bg-emerald-50 text-emerald-700",
    "bg-orange-50 text-orange-700",
    "bg-blue-50 text-blue-700",
    "bg-rose-50 text-rose-700",
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Top bar */}
      <header className="sticky top-0 z-30 bg-background/95 backdrop-blur border-b border-border">
        <div className="max-w-[1100px] mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link to="/leads">
              <Button variant="ghost" size="icon" className="h-8 w-8"><ArrowLeft className="w-4 h-4" /></Button>
            </Link>
            <span className="text-sm text-muted-foreground">Mes leads / Fiche entreprise</span>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="gap-2" onClick={() => setEditOpen(true)}>
              <Pencil className="w-3.5 h-3.5" /> Modifier
            </Button>
            <Button variant="outline" size="sm" className="gap-2 hover:bg-destructive/10 hover:text-destructive">
              <Trash2 className="w-3.5 h-3.5" /> Supprimer
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-[1100px] mx-auto px-6 py-6 space-y-6">
        {/* Hero */}
        <Card className="p-6">
          <div className="flex items-start justify-between flex-wrap gap-4">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-xl bg-blue-50 flex items-center justify-center text-tacir-blue font-semibold text-xl flex-shrink-0">
                {initials}
              </div>
              <div>
                <h1 className="text-xl font-semibold text-foreground">{displayLead.nom}</h1>
                <p className="text-sm text-muted-foreground mt-0.5">
                  SIREN {displayLead.siren} · {displayLead.ville}, {displayLead.pays}
                </p>
                <div className="flex flex-wrap gap-1.5 mt-2">
                  <SegmentBadge segment={displayLead.segment} />
                  <StatusBadge status={displayLead.status} />
                  {displayLead.hasBoamp && <BoampBadge />}
                </div>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-center p-3 rounded-xl bg-muted/50 min-w-[70px]">
                <ScoreRing score={displayLead.score} size="md" />
                <p className="text-[10px] text-muted-foreground mt-1">Score</p>
              </div>
              <div className="text-center p-3 rounded-xl bg-muted/50 min-w-[70px]">
                <p className="text-lg font-semibold text-foreground">{displayLead.probaConversion}%</p>
                <p className="text-[10px] text-muted-foreground">Proba.</p>
              </div>
              <div className="text-center p-3 rounded-xl bg-muted/50 min-w-[70px]">
                <p className="text-lg font-semibold text-foreground">{displayLead.completude}%</p>
                <p className="text-[10px] text-muted-foreground">Complétude</p>
              </div>
            </div>
          </div>
        </Card>

        {/* Two-column sections */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Identité */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg bg-blue-50 flex items-center justify-center">
                  <FileText className="w-3.5 h-3.5 text-tacir-blue" />
                </div>
                Identité
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="space-y-0">
                <InfoRow label="SIREN" value={displayLead.siren} />
                <InfoRow label="SIRET" value={displayLead.siret} />
                <InfoRow label="Identifiant" value={displayLead.identifiant} />
                <InfoRow label="Taille" value={displayLead.tailleEntreprise} badge />
                <InfoRow label="Forme juridique" value={displayLead.formeJuridique} />
                <InfoRow label="Date de création" value={displayLead.dateCreationFormatted} />
                <InfoRow label="Secteur d'activité" value={displayLead.secteurActivite} />
                <InfoRow label="Chiffre d'affaires" value={displayLead.caFormatted} highlight />
                <InfoRow label="Nb locaux" value={displayLead.nbLocaux?.toString() ?? "—"} />
              </div>
            </CardContent>
          </Card>

          {/* Adresse & Contact */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg bg-emerald-50 flex items-center justify-center">
                  <MapPin className="w-3.5 h-3.5 text-emerald-600" />
                </div>
                Adresse & contact
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="space-y-0">
                <InfoRow label="Adresse" value="Non renseigné" muted />
                <InfoRow label="Code postal" value={displayLead.codePostal} />
                <InfoRow label="Ville" value={displayLead.ville} />
                <InfoRow label="Région" value="Non renseigné" muted />
                <InfoRow label="Pays" value={displayLead.pays} />
                <InfoRow label="Email" value={displayLead.email} link />
                <InfoRow label="Téléphone" value={displayLead.telephone} link />
                <InfoRow label="Site web" value="Non renseigné" muted />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Dirigeants */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-purple-50 flex items-center justify-center">
                <Users className="w-3.5 h-3.5 text-purple-600" />
              </div>
              Dirigeants & contacts ({displayLead.nbDirigeants})
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            {displayLead.dirigeants.length === 0 ? (
              <p className="text-sm text-muted-foreground italic">Aucun dirigeant renseigné</p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {displayLead.dirigeants.map((d, i) => (
                  <DirigeantCard key={d.id} dirigeant={d} colorClass={AVATAR_COLORS[i % AVATAR_COLORS.length]} />
                ))}
              </div>
            )}
            {/* Completude contacts */}
            <div className="flex items-center gap-3 mt-4 pt-4 border-t border-border">
              <span className="text-[11px] text-muted-foreground">Complétude contacts</span>
              <div className="flex-1 h-1.5 rounded-full bg-muted overflow-hidden">
                <div
                  className="h-full rounded-full bg-emerald-500"
                  style={{ width: `${Math.min(100, displayLead.dirigeants.filter((d) => d.linkedinUrl).length / Math.max(1, displayLead.nbDirigeants) * 100)}%` }}
                />
              </div>
              <span className="text-xs font-medium text-emerald-600">
                {Math.round(displayLead.dirigeants.filter((d) => d.linkedinUrl).length / Math.max(1, displayLead.nbDirigeants) * 100)}%
              </span>
            </div>
          </CardContent>
        </Card>

        {/* Indicateurs métier */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-amber-50 flex items-center justify-center">
                <BarChart3 className="w-3.5 h-3.5 text-amber-600" />
              </div>
              Indicateurs métier
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <Metric icon={Target} label="Score" value={`${displayLead.score}/100`} />
              <Metric icon={TrendingUp} label="Proba. conversion" value={`${displayLead.probaConversion}%`} />
              <Metric icon={Activity} label="Complétude" value={`${displayLead.completude}%`} />
              <Metric icon={Users} label="Nb dirigeants" value={`${displayLead.nbDirigeants}`} />
              <Metric icon={Linkedin} label="LinkedIn" value={displayLead.hasLinkedinDirigeant ? "Oui" : "Non"} />
              <Metric icon={Mail} label="Email" value={displayLead.hasEmail ? "Oui" : "Non"} />
              <Metric icon={Phone} label="Téléphone" value={displayLead.hasTelephone ? "Oui" : "Non"} />
              <Metric icon={Clock} label="Fraîcheur" value={displayLead.dateScrapingFormatted} />
            </div>
          </CardContent>
        </Card>

        {/* Métadonnées */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-semibold flex items-center gap-2 text-muted-foreground">
              <div className="w-7 h-7 rounded-lg bg-muted flex items-center justify-center">
                <Database className="w-3.5 h-3.5 text-muted-foreground" />
              </div>
              Métadonnées & source
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-x-6 gap-y-0">
              <InfoRow label="Date création entreprise" value={displayLead.dateCreationFormatted} />
              <InfoRow label="Dernière modif. site" value={displayLead.dateDerniereModifFormatted} />
              <InfoRow label="Date scraping" value={displayLead.dateScrapingFormatted} />
              <InfoRow label="Créé le" value={displayLead.createdAt ? formatDateFR(displayLead.createdAt) : "—"} />
              <InfoRow label="Mis à jour le" value={displayLead.updatedAt ? formatDateFR(displayLead.updatedAt) : "—"} />
              <InfoRow label="Raw Lead ID" value={displayLead.rawLeadId ?? "—"} />
            </div>
            {displayLead.sources && (
              <div className="mt-3 pt-3 border-t border-border">
                <p className="text-[11px] text-muted-foreground mb-1">Sources</p>
                <p className="text-xs font-mono text-muted-foreground bg-muted/50 rounded-lg p-2 overflow-x-auto">
                  {JSON.stringify(displayLead.sources, null, 0).slice(0, 200)}…
                </p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Action buttons */}
        <div className="flex justify-end gap-3 pb-8">
          <Button variant="outline" className="gap-2">
            <RefreshCw className="w-3.5 h-3.5" /> Prospects similaires
          </Button>
          <Button className="gap-2">
            <TrendingUp className="w-3.5 h-3.5" /> Analyser le potentiel
          </Button>
        </div>
      </main>

      <LeadEditModal
        lead={editOpen ? displayLead : null}
        open={editOpen}
        onClose={() => setEditOpen(false)}
        onSave={(id, updates) => {
          setCurrentLead({ ...displayLead, ...updates } as UILead);
          toast.success("Lead mis à jour");
        }}
      />
    </div>
  );
}

// ---- Sub-components ----

function InfoRow({ label, value, link, highlight, muted, badge }: {
  label: string; value: string; link?: boolean; highlight?: boolean; muted?: boolean; badge?: boolean;
}) {
  const isMissing = value === "—" || value === "Non renseigné";
  return (
    <div className="flex items-center justify-between py-2 border-b border-border last:border-b-0">
      <span className="text-[11px] text-muted-foreground">{label}</span>
      {badge ? (
        <Badge variant="outline" className="text-[10px] bg-blue-50 text-tacir-blue border-blue-200">{value}</Badge>
      ) : (
        <span className={`text-xs font-medium text-right max-w-[200px] truncate ${
          isMissing || muted ? "text-muted-foreground italic" :
          link ? "text-tacir-blue" :
          highlight ? "text-emerald-600" :
          "text-foreground"
        }`}>
          {value}
        </span>
      )}
    </div>
  );
}

function DirigeantCard({ dirigeant, colorClass }: { dirigeant: UIDirigeant; colorClass: string }) {
  return (
    <div className="flex items-start gap-3 p-3 rounded-xl bg-muted/40 hover:bg-muted/60 transition-colors">
      <div className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-semibold flex-shrink-0 ${colorClass}`}>
        {dirigeant.initials}
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-foreground truncate">{dirigeant.fullName}</p>
        <p className="text-[11px] text-muted-foreground">{dirigeant.qualite}</p>
        <div className="flex items-center gap-3 mt-1.5 flex-wrap">
          <span className="text-[11px] text-muted-foreground italic">Email non renseigné</span>
          <span className="text-[11px] text-muted-foreground italic">Tél. non renseigné</span>
        </div>
      </div>
      <div className="flex flex-col items-end gap-1 flex-shrink-0">
        {dirigeant.age && (
          <div className="text-center">
            <span className="text-base font-semibold text-foreground">{dirigeant.age}</span>
            <span className="text-[10px] text-muted-foreground block">ans</span>
          </div>
        )}
        {dirigeant.linkedinUrl && (
          <a href={dirigeant.linkedinUrl} target="_blank" rel="noreferrer" className="text-blue-600 hover:text-blue-800">
            <Linkedin className="w-4 h-4" />
          </a>
        )}
      </div>
    </div>
  );
}

function Metric({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) {
  return (
    <div className="p-3 rounded-xl bg-muted/40 text-center">
      <Icon className="w-4 h-4 text-muted-foreground mx-auto mb-1" />
      <p className="text-sm font-semibold text-foreground">{value}</p>
      <p className="text-[10px] text-muted-foreground">{label}</p>
    </div>
  );
}
